
[[constraint]]
  name = "github.com/maorfr/helm-plugin-utils"
  version = "0.1.2"

[[constraint]]
  name = "github.com/maorfr/helm-restore"
  version = "0.1.0"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "2.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  go-tests = true
  unused-packages = true
